version: "3"

services:
  backend:
    image: puremlhq/pureml_backend:local-base
    environment:
      - PURE_SITE_BASE_URL=http://localhost:3000
    ports:
      - 8080:8080
    volumes:
      - pureml-data:/pureml_backend/data

  frontend:
    image: puremlhq/pureml_frontend:dev
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080/api/
      - NEXT_PUBLIC_AIRTABLE_API_KEY={YOUR_AIRTABLE_API_KEY}
    ports:
      - 3000:3000
    links:
      - backend

volumes:
  pureml-data:
